# Generated by Django 5.1.2 on 2025-03-25 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('war_risk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='region',
            table='Region',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
