# Generated by Django 5.1.2 on 2025-05-04 21:03

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('war_risk', '0002_alter_region_table_alter_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='GunImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(), upload_to='')),
            ],
        ),
    ]
