# Generated by Django 5.1.2 on 2025-05-04 23:13

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('war_risk', '0003_gunimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gunimage',
            name='file',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(), upload_to=''),
        ),
    ]
